let countryList = {
    "USD": { countryCode: "US", countryName: "United States Dollar" },
    "AED": { countryCode: "AE", countryName: "United Arab Emirates Dirham" },
    "AFN": { countryCode: "AF", countryName: "Afghan Afghani" },
    "ALL": { countryCode: "AL", countryName: "Albanian Lek" },
    "AMD": { countryCode: "AM", countryName: "Armenian Dram" },
    "ANG": { countryCode: "AN", countryName: "Netherlands Antillean Guilder" },
    "AOA": { countryCode: "AO", countryName: "Angolan Kwanza" },
    "ARS": { countryCode: "AR", countryName: "Argentine Peso" },
    "AUD": { countryCode: "AU", countryName: "Australian Dollar" },
    "AWG": { countryCode: "AW", countryName: "Aruban Florin" },
    "AZN": { countryCode: "AZ", countryName: "Azerbaijani Manat" },
    "BAM": { countryCode: "BA", countryName: "Bosnia and Herzegovina Convertible Mark" },
    "BBD": { countryCode: "BB", countryName: "Barbadian Dollar" },
    "BDT": { countryCode: "BD", countryName: "Bangladeshi Taka" },
    "BGN": { countryCode: "BG", countryName: "Bulgarian Lev" },
    "BHD": { countryCode: "BH", countryName: "Bahraini Dinar" },
    "BIF": { countryCode: "BI", countryName: "Burundian Franc" },
    "BMD": { countryCode: "BM", countryName: "Bermudian Dollar" },
    "BND": { countryCode: "BN", countryName: "Brunei Dollar" },
    "BOB": { countryCode: "BO", countryName: "Bolivian Boliviano" },
    "BRL": { countryCode: "BR", countryName: "Brazilian Real" },
    "BSD": { countryCode: "BS", countryName: "Bahamian Dollar" },
    "BTN": { countryCode: "BT", countryName: "Bhutanese Ngultrum" },
    "BWP": { countryCode: "BW", countryName: "Botswana Pula" },
    "BYN": { countryCode: "BY", countryName: "Belarusian Ruble" },
    "BZD": { countryCode: "BZ", countryName: "Belize Dollar" },
    "CAD": { countryCode: "CA", countryName: "Canadian Dollar" },
    "CDF": { countryCode: "CD", countryName: "Congolese Franc" },
    "CHF": { countryCode: "CH", countryName: "Swiss Franc" },
    "CLP": { countryCode: "CL", countryName: "Chilean Peso" },
    "CNY": { countryCode: "CN", countryName: "Chinese Yuan" },
    "COP": { countryCode: "CO", countryName: "Colombian Peso" },
    "CRC": { countryCode: "CR", countryName: "Costa Rican Colón" },
    "CUP": { countryCode: "CU", countryName: "Cuban Peso" },
    "CVE": { countryCode: "CV", countryName: "Cape Verdean Escudo" },
    "CZK": { countryCode: "CZ", countryName: "Czech Koruna" },
    "DJF": { countryCode: "DJ", countryName: "Djiboutian Franc" },
    "DKK": { countryCode: "DK", countryName: "Danish Krone" },
    "DOP": { countryCode: "DO", countryName: "Dominican Peso" },
    "DZD": { countryCode: "DZ", countryName: "Algerian Dinar" },
    "EGP": { countryCode: "EG", countryName: "Egyptian Pound" },
    "ERN": { countryCode: "ER", countryName: "Eritrean Nakfa" },
    "ETB": { countryCode: "ET", countryName: "Ethiopian Birr" },
    "EUR": { countryCode: "EU", countryName: "Euro" },
    "FJD": { countryCode: "FJ", countryName: "Fijian Dollar" },
    "FKP": { countryCode: "FK", countryName: "Falkland Islands Pound" },
    "FOK": { countryCode: "FO", countryName: "Faroese Króna" },
    "GBP": { countryCode: "GB", countryName: "British Pound Sterling" },
    "GEL": { countryCode: "GE", countryName: "Georgian Lari" },
    "GGP": { countryCode: "GG", countryName: "Guernsey Pound" },
    "GHS": { countryCode: "GH", countryName: "Ghanaian Cedi" },
    "GIP": { countryCode: "GI", countryName: "Gibraltar Pound" },
    "GMD": { countryCode: "GM", countryName: "Gambian Dalasi" },
    "GNF": { countryCode: "GN", countryName: "Guinean Franc" },
    "GTQ": { countryCode: "GT", countryName: "Guatemalan Quetzal" },
    "GYD": { countryCode: "GY", countryName: "Guyanese Dollar" },
    "HKD": { countryCode: "HK", countryName: "Hong Kong Dollar" },
    "HNL": { countryCode: "HN", countryName: "Honduran Lempira" },
    "HRK": { countryCode: "HR", countryName: "Croatian Kuna" },
    "HTG": { countryCode: "HT", countryName: "Haitian Gourde" },
    "HUF": { countryCode: "HU", countryName: "Hungarian Forint" },
    "IDR": { countryCode: "ID", countryName: "Indonesian Rupiah" },
    "ILS": { countryCode: "IL", countryName: "Israeli New Shekel" },
    "IMP": { countryCode: "IM", countryName: "Isle of Man Pound" },
    "INR": { countryCode: "IN", countryName: "Indian Rupee" },
    "IQD": { countryCode: "IO", countryName: "Iraqi Dinar" },
    "IRR": { countryCode: "IR", countryName: "Iranian Rial" },
    "ISK": { countryCode: "IS", countryName: "Icelandic Króna" },
    "JEP": { countryCode: "JE", countryName: "Jersey Pound" },
    "JMD": { countryCode: "JM", countryName: "Jamaican Dollar" },
    "JOD": { countryCode: "JO", countryName: "Jordanian Dinar" },
    "JPY": { countryCode: "JP", countryName: "Japanese Yen" },
    "KES": { countryCode: "KE", countryName: "Kenyan Shilling" },
    "KGS": { countryCode: "KG", countryName: "Kyrgyzstani Som" },
    "KHR": { countryCode: "KH", countryName: "Cambodian Riel" },
    "KID": { countryCode: "KI", countryName: "Kiribati Dollar" },
    "KMF": { countryCode: "KM", countryName: "Comorian Franc" },
    "KRW": { countryCode: "KR", countryName: "South Korean Won" },
    "KWD": { countryCode: "KW", countryName: "Kuwaiti Dinar" },
    "KYD": { countryCode: "KY", countryName: "Cayman Islands Dollar" },
    "KZT": { countryCode: "KZ", countryName: "Kazakhstani Tenge" },
    "LAK": { countryCode: "LA", countryName: "Laotian Kip" },
    "LBP": { countryCode: "LB", countryName: "Lebanese Pound" },
    "LKR": { countryCode: "LK", countryName: "Sri Lankan Rupee" },
    "LRD": { countryCode: "LR", countryName: "Liberian Dollar" },
    "LSL": { countryCode: "LS", countryName: "Lesotho Loti" },
    "LYD": { countryCode: "LY", countryName: "Libyan Dinar" },
    "MAD": { countryCode: "MA", countryName: "Moroccan Dirham" },
    "MDL": { countryCode: "MD", countryName: "Moldovan Leu" },
    "MGA": { countryCode: "MG", countryName: "Malagasy Ariary" },
    "MKD": { countryCode: "MK", countryName: "Macedonian Denar" },
    "MMK": { countryCode: "MM", countryName: "Myanmar Kyat" },
    "MNT": { countryCode: "MN", countryName: "Mongolian Tugrik" },
    "MOP": { countryCode: "MO", countryName: "Macanese Pataca" },
    "MRU": { countryCode: "MR", countryName: "Mauritanian Ouguiya" },
    "MUR": { countryCode: "MU", countryName: "Mauritian Rupee" },
    "MVR": { countryCode: "MV", countryName: "Maldivian Rufiyaa" },
    "MWK": { countryCode: "MW", countryName: "Malawian Kwacha" },
    "MXN": { countryCode: "MX", countryName: "Mexican Peso" },
    "MYR": { countryCode: "MY", countryName: "Malaysian Ringgit" },
    "MZN": { countryCode: "MZ", countryName: "Mozambican Metical" },
    "NAD": { countryCode: "NA", countryName: "Namibian Dollar" },
    "NGN": { countryCode: "NG", countryName: "Nigerian Naira" },
    "NIO": { countryCode: "NI", countryName: "Nicaraguan Córdoba" },
    "NOK": { countryCode: "NO", countryName: "Norwegian Krone" },
    "NPR": { countryCode: "NP", countryName: "Nepalese Rupee" },
    "NZD": { countryCode: "NZ", countryName: "New Zealand Dollar" },
    "OMR": { countryCode: "OM", countryName: "Omani Rial" },
    "PAB": { countryCode: "PA", countryName: "Panamanian Balboa" },
    "PEN": { countryCode: "PE", countryName: "Peruvian Nuevo Sol" },
    "PGK": { countryCode: "PG", countryName: "Papua New Guinean Kina" },
    "PHP": { countryCode: "PH", countryName: "Philippine Peso" },
    "PKR": { countryCode: "PK", countryName: "Pakistani Rupee" },
    "PLN": { countryCode: "PL", countryName: "Polish Złoty" },
    "PYG": { countryCode: "PY", countryName: "Paraguayan Guarani" },
    "QAR": { countryCode: "QA", countryName: "Qatari Riyal" },
    "RON": { countryCode: "RO", countryName: "Romanian Leu" },
    "RSD": { countryCode: "RS", countryName: "Serbian Dinar" },
    "RUB": { countryCode: "RU", countryName: "Russian Ruble" },
    "RWF": { countryCode: "RW", countryName: "Rwandan Franc" },
    "SAR": { countryCode: "SA", countryName: "Saudi Riyal" },
    "SBD": { countryCode: "SB", countryName: "Solomon Islands Dollar" },
    "SCR": { countryCode: "SC", countryName: "Seychellois Rupee" },
    "SDG": { countryCode: "SD", countryName: "Sudanese Pound" },
    "SEK": { countryCode: "SE", countryName: "Swedish Krona" },
    "SGD": { countryCode: "SG", countryName: "Singapore Dollar" },
    "SHP": { countryCode: "SH", countryName: "Saint Helena Pound" },
    "SLE": { countryCode: "SL", countryName: "Sierra Leonean Leone" },
    "SLL": { countryCode: "SL", countryName: "Sierra Leonean Leone" },
    "SOS": { countryCode: "SO", countryName: "Somali Shilling" },
    "SRD": { countryCode: "SR", countryName: "Surinamese Dollar" },
    "SSP": { countryCode: "SS", countryName: "South Sudanese Pound" },
    "STN": { countryCode: "ST", countryName: "São Tomé and Príncipe Dobra" },
    "SYP": { countryCode: "SY", countryName: "Syrian Pound" },
    "SZL": { countryCode: "SZ", countryName: "Swazi Lilangeni" },
    "THB": { countryCode: "TH", countryName: "Thai Baht" },
    "TJS": { countryCode: "TJ", countryName: "Tajikistani Somoni" },
    "TMT": { countryCode: "TM", countryName: "Turkmenistani Manat" },
    "TND": { countryCode: "TN", countryName: "Tunisian Dinar" },
    "TOP": { countryCode: "TO", countryName: "Tongan Pa'anga" },
    "TRY": { countryCode: "TR", countryName: "Turkish Lira" },
    "TTD": { countryCode: "TT", countryName: "Trinidad and Tobago Dollar" },
    "TVD": { countryCode: "TV", countryName: "Tuvaluan Dollar" },
    "TWD": { countryCode: "TW", countryName: "New Taiwan Dollar" },
    "TZS": { countryCode: "TZ", countryName: "Tanzanian Shilling" },
    "UAH": { countryCode: "UA", countryName: "Ukrainian Hryvnia" },
    "UGX": { countryCode: "UG", countryName: "Ugandan Shilling" },
    "UYU": { countryCode: "UY", countryName: "Uruguayan Peso" },
    "UZS": { countryCode: "UZ", countryName: "Uzbekistani Som" },
    "VES": { countryCode: "VE", countryName: "Venezuelan Bolívar" },
    "VND": { countryCode: "VN", countryName: "Vietnamese Đồng" },
    "VUV": { countryCode: "VU", countryName: "Vanuatu Vatu" },
    "WST": { countryCode: "WS", countryName: "Samoan Tala" },
    "XAF": { countryCode: "XA", countryName: "Central African CFA Franc" },
    "XCD": { countryCode: "XC", countryName: "East Caribbean Dollar" },
    "XDR": { countryCode: "XD", countryName: "Special Drawing Rights" },
    "XOF": { countryCode: "XO", countryName: "West African CFA Franc" },
    "XPF": { countryCode: "XP", countryName: "CFP Franc" },
    "YER": { countryCode: "YE", countryName: "Yemeni Rial" },
    "ZAR": { countryCode: "ZA", countryName: "South African Rand" },
    "ZMW": { countryCode: "ZM", countryName: "Zambian Kwacha" },
    "ZWL": { countryCode: "ZW", countryName: "Zimbabwean Dollar" }, 
};



  
